[precipitation_obs]
git-tree-sha1 = "7486bf32e9352493f69364aead26f01eaf90d2af"
lazy = true

    [[precipitation_obs.download]]
    sha256 = "463ebc1886c4e0be9656656da699f2cbb87d7c2568d5e81277c0c8a415dc8143"
    url = "https://caltech.box.com/shared/static/j63uak557kw7tlzb3dgwifoaeczekzm4.gz"
