[precipitation_obs]
git-tree-sha1 = "5f0075f042bc83b580d2c4f725f851d8e0b9c20a"

    [[precipitation_obs.download]]
    sha256 = "1aea361ee1c2636bd5c4cc343202dab814d246a7e0356a9caac9fd9c7cf3821c"
    url = "https://caltech.box.com/shared/static/j63uak557kw7tlzb3dgwifoaeczekzm4.gz"

[radiation_obs]
git-tree-sha1 = "945e31f8028a581f7e8435cb691462124484567a"

[era5_monthly_averages_surface_single_level_1979_2024]
git-tree-sha1 = "6cddb07eeee2dd46dc5a19e9b2f706302ddba2c9"

    [[era5_monthly_averages_surface_single_level_1979_2024.download]]
    sha256 = "46b422722d98c89c6bc0b8641bff259db1caee253f45389ddf9eb9c2d31ed605"
    url = "https://caltech.box.com/shared/static/jbgtyt6oq9lxvk8il5zzck6k581q7f3k.gz"

[era5_monthly_averages_pressure_levels_1979_2024]
git-tree-sha1 = "dd7ee9500805f590f8fc4c00bfc373eeb7a01587"

[cmip_model_rmse]
git-tree-sha1 = "53a27731c0a2ec60756af24e4c60ac37da4a32bc"

    [[cmip_model_rmse.download]]
    sha256 = "3e8fa41df226dda9d375f8cb9dbeee3e10f9fceabcad2c7b91c9633b489b0437"
    url = "https://caltech.box.com/shared/static/lmzvnjkxctlb0fanieeqxll0vdrbei9e.gz"
