[zd_rayleigh]
value = 40000.0

[zd_viscous]
value = 40000.0

[alpha_rayleigh_sgs_tracer]
value = 1e-3

[EDMF_surface_area]
value = 0.06399178163606391

[min_area_limiter_scale]
value = 0

[max_area_limiter_scale]
value = 0

[EDMF_min_area]
value = 1.0e-5

[EDMF_max_area]
value = 0.7

[entr_coeff]
value = 0

#[entr_param_vec]
#value = [0, 0.1759425797637972, -4.15529994350738, 0, 0, 0.23]

[entr_param_vec]
value = [-4.040163221677218, -1.0682715155669829, 0.5672537060381109]
type = "float"

[entr_mult_limiter_coeff]
value = 0.6022681998170195

[entr_inv_tau]
value = 1.0e-4
type = "float"

[detr_inv_tau]
value = 1.0e-4
type = "float"

[detr_coeff]
value = 0

[detr_buoy_coeff]
value = 0

[detr_vertdiv_coeff]
value = 1.0509954648159656
type = "float"

[detr_massflux_vertdiv_coeff]
value = 0

[entr_detr_limit_inv_tau]
value = 0.01

[pressure_normalmode_drag_coeff]
value = 8.002319316450539

[pressure_normalmode_buoy_coeff1]
value = 0.04592259632544556

[mixing_length_tke_surf_flux_coeff]
value = 2.683648880020378
type = "float"

[mixing_length_diss_coeff]
value = 0.3365126342962741
type = "float"

[mixing_length_eddy_viscosity_coefficient]
value = 0.22932702255841497
type = "float"

[mixing_length_Prandtl_number_0]
value = 0.5168130504404477

[mixing_length_static_stab_coeff]
value = 0.35509778819311516

[precipitation_timescale]
value = 927.3052231536808
type = "float"

[Tq_correlation_coefficient]
value = 0.2746535098693904
type = "float"

[diagnostic_covariance_coeff]
value = 2.310846057324733
type = "float"

[supersaturation_precipitation_threshold]
value = 0.02
