[alpha_rayleigh_w]
value = 10.0

[zd_rayleigh]
value = 40000.0

[zd_viscous]
value = 40000.0

[mixing_length_Prandtl_maximum]
value = 4.2

[mixing_length_eddy_viscosity_coefficient]
value = 0.5892594727125273

[mixing_length_tke_surf_flux_coeff]
value = 0.3331950998157493

[mixing_length_diss_coeff]
value = 0.04640288100600733

[mixing_length_Prandtl_number_0]
value = 2.909243754318121

[mixing_length_static_stab_coeff]
value = 0.29736273245468714

[precipitation_timescale]
value = 1200

#[Tq_correlation_coefficient]
#value = -1
