[alpha_rayleigh_w]
value = 10.0

[zd_rayleigh]
value = 40000.0

[zd_viscous]
value = 40000.0

[entr_inv_tau]
value = 0.002

[entr_coeff]
value = 0

[detr_inv_tau]
value = 0

[detr_buoy_coeff]
value = 0.12

[detr_vertdiv_coeff]
value = 0.6

[min_area_limiter_scale]
value = 0

[max_area_limiter_scale]
value = 0

[mixing_length_Prandtl_maximum]
value = 4.2

[Tq_correlation_coefficient]
value = -1

[precipitation_timescale]
value = 1200

[diagnostic_covariance_coeff]
value = 2.1

[supersaturation_precipitation_threshold]
value = 0.02

#[prescribed_cloud_droplet_number_concentration]
#value = 3e8

#[ice_cloud_effective_radius]
#value = 20e-6
