[alpha_rayleigh_w]
value = 10.0

[zd_rayleigh]
value = 40000.0

[zd_viscous]
value = 40000.0

[mixing_length_Prandtl_maximum]
value = 4.2

[tracer_vertical_diffusion_factor]
value = 0

[condensation_evaporation_timescale]
value = 150

[sublimation_deposition_timescale]
value = 150

[snow_autoconversion_timescale]
value = 1e4

[rain_autoconversion_timescale]
value = 150

[temperature_water_freeze]
value = 100.0
