[zd_rayleigh]
value = 40000.0
type = "float"

[zd_viscous]
value = 40000.0
type = "float"

[alpha_rayleigh_w]
value = 10.0
type = "float"

[EDMF_surface_area]
value = 0.06399178163606391
type = "float"

[min_area_limiter_scale]
value = 0
type = "float"

[max_area_limiter_scale]
value = 0
type = "float"

[entr_coeff]
value = 0
type = "float"

#[entr_param_vec]
#value = [-17.63892707098534, 18.77897708611115, 0.31250294925628486]
#type = "float"

#[entr_mult_limiter_coeff]
#value = 0.8490142904088219
#type = "float"

#[entr_inv_tau]
#value = 0.00010586970154632861
#type = "float"

[detr_inv_tau]
value = 0
type = "float"

#[detr_vertdiv_coeff]
#value = 0.8
#type = "float"

[detr_buoy_coeff]
value = 0.12274545130376595
type = "float"

[pressure_normalmode_drag_coeff]
value = 6.212142257129916
type = "float"

[pressure_normalmode_buoy_coeff1]
value = 0.1469145574108413
type = "float"

#[mixing_length_eddy_viscosity_coefficient]
#value = 1.239591763940756
#type = "float"

#[mixing_length_tke_surf_flux_coeff]
#value = 0.3331950998157493
#type = "float"

#[mixing_length_diss_coeff]
#value = 0.04640288100600733
#type = "float"

[mixing_length_Prandtl_number_0]
value = 1.2595756943690926
type = "float"

[mixing_length_static_stab_coeff]
value = 0.3285376450623933
type = "float"

#[precipitation_timescale]
#value = 1200
#type = "float"

#[Tq_correlation_coefficient]
#value = -1
#type = "float"

#[diagnostic_covariance_coeff]
#value = 2.1
#type = "float"
