[zd_rayleigh]
value = 40000.0

[zd_viscous]
value = 40000.0

[alpha_rayleigh_sgs_tracer]
value = 1e-3

[EDMF_min_area]
value = 1.0e-5

[EDMF_max_area]
value = 0.7

[entr_inv_tau]
value = 0.0002

[entr_coeff]
value = 0.2

[min_area_limiter_scale]
value = 0

[min_area_limiter_power]
value = 100

[detr_inv_tau]
value = 0

[detr_coeff]
value = 0

[detr_buoy_coeff]
value = 0

[detr_vertdiv_coeff]
value = 0

[detr_massflux_vertdiv_coeff]
value = 1

[pressure_normalmode_drag_coeff]
value = 40.0

[tracer_vertical_diffusion_factor]
value = 0

[condensation_evaporation_timescale]
value = 100

[sublimation_deposition_timescale]
value = 100
