[alpha_rayleigh_w]
value = 10.0

[zd_rayleigh]
value = 40000.0

[zd_viscous]
value = 40000.0

[precipitation_timescale]
value = 600

[entr_inv_tau]
value = 0.002

[entr_coeff]
value = 0

[detr_inv_tau]
value = 0

[detr_buoy_coeff]
value = 0.12

[detr_vertdiv_coeff]
value = 0.6

[min_area_limiter_scale]
value = 0

[max_area_limiter_scale]
value = 0

[mixing_length_Prandtl_maximum]
value = 4.2

[tracer_vertical_diffusion_factor]
value = 0

[condensation_evaporation_timescale]
value = 150

[sublimation_deposition_timescale]
value = 150

[snow_autoconversion_timescale]
value = 1e3

[rain_autoconversion_timescale]
value = 150
