[zd_rayleigh]
value = 40000.0

[zd_viscous]
value = 40000.0

[alpha_rayleigh_sgs_tracer]
value = 1e-3

[EDMF_surface_area]
value = 0.06399178163606391

[min_area_limiter_scale]
value = 0

[max_area_limiter_scale]
value = 0

[EDMF_min_area]
value = 1.0e-5

[EDMF_max_area]
value = 0.7

[entr_coeff]
value = 0

[entr_param_vec]
value = [0, 0.1759425797637972, -4.15529994350738, 0, 0, 0.23034829797200007]

[entr_mult_limiter_coeff]
value = 0.6022681998170195

[entr_inv_tau]
value = 1.0e-4

[detr_inv_tau]
value = 1.0e-4

[detr_coeff]
value = 0

[detr_buoy_coeff]
value = 0

[detr_vertdiv_coeff]
value = 1

[detr_massflux_vertdiv_coeff]
value = 0

[entr_detr_limit_inv_tau]
value = 0.01

[pressure_normalmode_drag_coeff]
value = 8.002319316450539

[pressure_normalmode_buoy_coeff1]
value = 0.04592259632544556

[mixing_length_tke_surf_flux_coeff]
value = 0.3331950998157493

[mixing_length_diss_coeff]
value = 0.04640288100600733

[mixing_length_eddy_viscosity_coefficient]
#value = 1.497382613786804
value = 0.4

[mixing_length_Prandtl_number_0]
value = 0.5168130504404477

[mixing_length_static_stab_coeff]
value = 0.35509778819311516

[precipitation_timescale]
value = 1350

[Tq_correlation_coefficient]
value = -0.6

[diagnostic_covariance_coeff]
value = 2.1

[supersaturation_precipitation_threshold]
value = 0.02
