[zd_rayleigh]
value = 40000.0

[zd_viscous]
value = 40000.0

[alpha_rayleigh_w]
value = 10.0

[EDMF_surface_area]
value = 0.06399178163606391

[min_area_limiter_scale]
value = 0

[max_area_limiter_scale]
value = 0

[entr_coeff]
value = 0

[entr_param_vec]
value = [-20.29437694493032, -22.269204417686513, -0.8]

[entr_mult_limiter_coeff]
value = 0.4641383877134538

[entr_inv_tau]
value = 0.004362201402729065

[detr_inv_tau]
value = 0

[detr_vertdiv_coeff]
value = 0.6

[detr_buoy_coeff]
value = 0.12

#[pressure_normalmode_drag_coeff]
#value = 0.22685176632582243

#[pressure_normalmode_buoy_coeff1]
#value = 0.024795188237279258

[mixing_length_Prandtl_maximum]
value = 4.2

[mixing_length_eddy_viscosity_coefficient]
value = 0.5892594727125273

[mixing_length_tke_surf_flux_coeff]
value = 0.3331950998157493

[mixing_length_diss_coeff]
value = 0.04640288100600733

[mixing_length_Prandtl_number_0]
value = 2.909243754318121

[mixing_length_static_stab_coeff]
value = 0.29736273245468714

[precipitation_timescale]
value = 1200

[Tq_correlation_coefficient]
value = -1

[diagnostic_covariance_coeff]
value = 2.1

[supersaturation_precipitation_threshold]
value = 0.02
