[zd_rayleigh]
value = 40000.0
type = "float"

[zd_viscous]
value = 40000.0
type = "float"

[alpha_rayleigh_w]
value = 10.0
type = "float"

[EDMF_surface_area]
value = 0.06399178163606391
type = "float"

[min_area_limiter_scale]
value = 0
type = "float"

[max_area_limiter_scale]
value = 0
type = "float"

[entr_coeff]
value = 0
type = "float"

[entr_param_vec]
value = [-20.29437694493032, -22.269204417686513, -0.8]
type = "float"

[entr_mult_limiter_coeff]
value = 0.4641383877134538
type = "float"

[entr_inv_tau]
value = 0.004362201402729065
type = "float"

[detr_inv_tau]
value = 0
type = "float"

[detr_vertdiv_coeff]
value = 0.8
type = "float"

[detr_buoy_coeff]
value = 0.1
type = "float"

[mixing_length_Prandtl_maximum]
value = 4.2
type = "float"

[mixing_length_eddy_viscosity_coefficient]
value = 0.5892594727125273
type = "float"

[mixing_length_tke_surf_flux_coeff]
value = 0.3331950998157493
type = "float"

[mixing_length_diss_coeff]
value = 0.04640288100600733
type = "float"

[mixing_length_Prandtl_number_0]
value = 2.909243754318121
type = "float"

[mixing_length_static_stab_coeff]
value = 0.29736273245468714
type = "float"

#[precipitation_timescale]
#value = 1200
#type = "float"

#[Tq_correlation_coefficient]
#value = -1
#type = "float"

[diagnostic_covariance_coeff]
value = 2.1
type = "float"
