[alpha_rayleigh_w]
value = 10.0

[zd_rayleigh]
value = 40000.0

[zd_viscous]
value = 40000.0

[entr_inv_tau]
value = 0.001

[entr_coeff]
value = 0

[detr_inv_tau]
value = 0

[detr_buoy_coeff]
value = 0.12

[detr_vertdiv_coeff]
value = 0.6

[min_area_limiter_scale]
value = 0

[max_area_limiter_scale]
value = 0

[mixing_length_Prandtl_maximum]
value = 4.2

[tracer_vertical_diffusion_factor]
value = 0

[condensation_evaporation_timescale]
value = 150

[sublimation_deposition_timescale]
value = 150

[snow_autoconversion_timescale]
value = 1e3

[rain_autoconversion_timescale]
value = 150

[Variable_time_scale_autoconversion_coeff_alpha]
value = 2.09

#[rain_terminal_velocity_size_relation_coefficient_chiv]
#value = 0.213

#[rain_terminal_velocity_size_relation_coefficient_delv]
#value = 0.351

[rain_cross_section_size_relation_coefficient_chia]
value = 6.41

[rain_cross_section_size_relation_coefficient_dela]
value = 0.01

[rain_ventilation_coefficient_b]
value = 1.48
