[alpha_rayleigh_w]
value = 10.0
type = "float"

[zd_rayleigh]
value = 45000.0
type = "float"

[ice_albedo]
value = 0.7
type = "float"
description = "Albedo of ice (unitless)."

[zd_viscous]
value = 45000.0
type = "float"

[precipitation_timescale]
value = 600
type = "float"

[entr_inv_tau]
value = 0.002
type = "float"

[entr_coeff]
value = 0
type = "float"

[detr_inv_tau]
value = 0
type = "float"

[detr_buoy_coeff]
value = 0.12
type = "float"

[detr_vertdiv_coeff]
value = 0.6
type = "float"

[min_area_limiter_scale]
value = 0
type = "float"

[max_area_limiter_scale]
value = 0
type = "float"

[mixing_length_Prandtl_maximum]
value = 4.2
type = "float"

[land_bucket_capacity]
value = 0.8
type = "float"