[alpha_rayleigh_w]
value = 10.0

[zd_rayleigh]
value = 45000.0

[zd_viscous]
value = 45000.0

[precipitation_timescale]
value = 1200

[entr_inv_tau]
value = 0.004362201402729065

[entr_param_vec]
value = [0, -20.29437694493032, -22.269204417686513, 0, 0, -0.8]

[entr_coeff]
value = 0

[detr_inv_tau]
value = 0

[detr_buoy_coeff]
value = 0.12

[detr_vertdiv_coeff]
value = 0.6

[min_area_limiter_scale]
value = 0

[max_area_limiter_scale]
value = 0

[mixing_length_Prandtl_maximum]
value = 4.2

[land_bucket_capacity]
value = 0.8
