moist: "equil"
vert_diff: "true"
rad: "gray"
energy_check: false
mode_name: "amip"
anim: true
t_end: "32days"
dt_save_to_sol: "1days"
dt_cpl: 400
dt: "400secs"
mono_surface: false
h_elem: 6
dt_save_restart: "5days"
precip_model: "0M"
run_name: "coarse_mpi_n2"
apply_limiter: true
job_id: "coarse_mpi_n2"
