FLOAT_TYPE: "Float32"
aerosol_radiation: true
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_allsky_diagedmf_0M.yml"
checkpoint_dt: "300days"
coupler_toml_file: "toml/amip_target_topo_diagedmf.toml"
dt: "120secs"
dt_cloud_fraction: "1hours"
dt_cpl: "120secs"
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
energy_check: false
insolation: "timevarying"
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
netcdf_output_at_levels: true
output_default_diagnostics: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
prescribe_ozone: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "300days"
topo_smoothing: true
topography: "Earth"
turb_flux_partition: "CombinedStateFluxesMOST"
