FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_diagedmf.yml"
bucket_albedo_type: "map_temporal"
checkpoint_dt: "1months"
coupler_toml: ["toml/amip_diagedmf_1m.toml"]
dt: "120secs"
dt_cloud_fraction: "1hours"
dt_cpl: "120secs"
dt_rad: "1hours"
energy_check: false
insolation: "timevarying"
mode_name: "amip"
moist: "nonequil"
precip_model: "1M"
netcdf_output_at_levels: true
output_default_diagnostics: true
rmse_check: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "366days"
topo_smoothing: true
topography: "Earth"
