FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/longrun_configs/longrun_aquaplanet_allsky_0M_earth.yml"
coupler_toml_file: "toml/amip.toml"
dt: "120secs"
dt_cloud_fraction: "1hours"
viscous_sponge: true
dt_cpl: 120
dt_rad: "1hours"
dt_save_state_to_disk: "20days"
energy_check: false
hourly_checkpoint: true
insolation: "timevarying"
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
netcdf_interpolate_z_over_msl: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "366days"
topo_smoothing: true
topography: "Earth"
turb_flux_partition: "CombinedStateFluxesMOST"
prescribe_ozone: true
aerosol_radiation: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, pr, edt, hfes]
    period: 2hours
