FLOAT_TYPE: "Float32"
aerosol_radiation: true
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_diagedmf.yml"
checkpoint_dt: "1months"
coupler_toml: ["toml/amip_diagedmf.toml"]
dt: "120secs"
dt_cloud_fraction: "1hours"
dt_cpl: "120secs"
dt_rad: "1hours"
energy_check: false
insolation: "timevarying"
land_model: "integrated"
mode_name: "amip"
netcdf_output_at_levels: true
output_default_diagnostics: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
rmse_check: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "366days"
topo_smoothing: true
topography: "Earth"
