FLOAT_TYPE: "Float32"
#aerosol_radiation: true
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_edonly.yml"
bucket_albedo_type: "map_temporal"
checkpoint_dt: "1days"
coupler_toml: ["toml/amip.toml"]
dt: "120secs"
dt_cloud_fraction: "1hours"
dt_cpl: "120secs"
dt_rad: "1hours"
energy_check: false
insolation: "timevarying"
#max_newton_iters_ode: 3
mode_name: "amip"
moist: "nonequil"
precip_model: "1M"
#prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
#restart_dir: "/scratch/clima/slurm-buildkite/climacoupler-coarse-nightly-amip/678/climacoupler-coarse-nightly-amip/experiments/ClimaEarth/output/amip_edonly_1M_gpu/checkpoints/"
#restart_t: 1468800
radiation_reset_rng_seed: true
rmse_check: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "31days"
topo_smoothing: true
topography: "Earth"
check_nan_every: 30
extra_atmos_diagnostics:
  - short_name: [ts, ta, pfull, rhoa, ua, va, wa, hfss, hfls, hur, hus, cl, clw, cli, husra, hussn, pr, tke]
    period: 1days
