FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_diagedmf.yml"
bucket_albedo_type: "map_temporal"
checkpoint_dt: "1months"
coupler_toml: ["toml/amip_diagedmf.toml"]
dt: "120secs"
dt_cloud_fraction: "1hours"
dt_cpl: "120secs"
dt_rad: "1hours"
energy_check: false
initial_condition: "AMIPFromERA5"
insolation: "timevarying"
land_model: "integrated"
mode_name: "amip"
netcdf_output_at_levels: true
output_default_diagnostics: true
rmse_check: true
sst_adjustment: 2.0
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "366days"
topo_smoothing: true
topography: "Earth"
