FLOAT_TYPE: "Float64"
atmos_config_file: "config/atmos_configs/climaatmos_edonly.yml"
bucket_albedo_type: "map_temporal"
checkpoint_dt: "720hours"
dt_atmos: "120secs" # 2 minutes
dt_cloud_fraction: "1hours"
dt_cpl: "120secs" # 2 minutes
dt_land: "120secs" # 2 minutes
dt_ocean: "120secs" # 2 minutes
dt_rad: "1hours"
dt_seaice: "120secs" # 2 minutes
energy_check: false
ice_model: "clima_seaice"
insolation: "timevarying"
mode_name: "cmip"
ocean_model: "oceananigans"
rmse_check: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "3days"
topo_smoothing: true
topography: "Earth"
