FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_edonly.yml"
bucket_albedo_type: "map_temporal"
checkpoint_dt: "720hours"
coupler_toml: ["toml/amip.toml"]
dt_atmos: "120secs" # 2 minutes
dt_cpl: "1800secs" # 30 minutes
dt_land: "360secs" # 6 minutes
dt_ocean: "1800secs" # 30 minutes
dt_seaice: "1800secs" # 30 minutes
energy_check: false
ice_model: "clima_seaice"
mode_name: "cmip"
netcdf_output_at_levels: true
output_default_diagnostics: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
radiation_reset_rng_seed: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "186days"
topo_smoothing: true
topography: "Earth"
use_itime: false
