aerosol_radiation: true
approximate_linear_solve_iters: 2
cloud_model: "quadrature_sgs"
co2_model: maunaloa
dt: "120secs"
dt_cloud_fraction: "1hours"
dt_rad: "1hours"
dt_save_state_to_disk: "30days"
dz_bottom: 30.0
edmfx_detr_model: "Generalized"
edmfx_entr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_sgs_diffusive_flux: true
edmfx_sgs_mass_flux: true
edmfx_upwinding: "first_order"
h_elem: 16
implicit_diffusion: true
insolation: "timevarying"
moist: "equil"
netcdf_output_at_levels: true
precip_model: "0M"
prescribe_ozone: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "DST02", "DST03", "DST04", "DST05", "OC1", "OC2", "SO4", "SSLT01", "SSLT02", "SSLT03", "SSLT04", "SSLT05"]
prognostic_tke: true
rad: "allskywithclear"
rayleigh_sponge: true
surface_setup: "DefaultMoninObukhov"
t_end: "120days"
toml: [toml/longrun_aquaplanet_diagedmf.toml]
turbconv: "diagnostic_edmfx"
viscous_sponge: true
z_elem: 63
z_max: 60000.0


# General
FLOAT_TYPE: "Float32"
atmos_config_file: "config/atmos_configs/climaatmos_diagedmf.yml"
coupler_toml: ["toml/amip.toml"]
start_date: "20100101"
dt: "60secs"
dt_cpl: "60secs"
z_elem: 39
t_end: "30days"
energy_check: false
mode_name: "amip"
# Surface
albedo_model: "CouplerAlbedo"
surface_setup: "PrescribedSurface"
bucket_albedo_type: "map_temporal"
topo_smoothing: true
topography: "Earth"
# Microphysics
#moist: "nonequil"
#precip_model: "1M"
moist: "equil"
precip_model: "0M"
cloud_model: "quadrature_sgs"
# Transport
implicit_diffusion: true
smagorinsky_lilly: "UV"
hyperdiff: "CAM_SE"
energy_q_tot_upwinding: "vanleer_limiter"
tracer_upwinding: "first_order"
edmfx_mse_q_tot_upwinding: "first_order"
edmfx_tracer_upwinding: "first_order"
# EDMF
prognostic_tke: true
edmfx_detr_model: "Generalized"
edmfx_entr_model: "PiGroups"
edmfx_nh_pressure: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
# Output
checkpoint_dt: "366days"
netcdf_output_at_levels: true
output_default_diagnostics: false
radiation_reset_rng_seed: true
coupler_output_dir: "/scratch/ajaruga/"
extra_atmos_diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, hussfc, evspsbl, pr, cape]
    period: 1days
    reduction: inst
  - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup]
    period: 1days
    reduction: inst
  - short_name: [entr, detr, lmix, bgrad, strain]
    period: 1days
    reduction: inst
#extra_atmos_diagnostics:
#  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, pr, cape, husra, hussn]
#    period: 1days
#    reduction: inst
#  - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup, clwup, cliup, husraup, hussnup]
#    period: 1days
#    reduction: inst
#  - short_name: [entr, detr, lmix, bgrad, strain]
#    period: 1days
#    reduction: inst
