FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_diagedmf.yml"
bucket_albedo_type: "map_temporal"
checkpoint_dt: "366days"
coupler_toml: ["toml/amip_diagedmf.toml"]
dt: "240secs"
dt_cpl: "240secs"
dz_bottom: 100.0
energy_check: false
h_elem: 8
mode_name: "amip"
netcdf_interpolation_num_points: [90, 45, 31]
netcdf_output_at_levels: true
output_default_diagnostics: true
radiation_reset_rng_seed: true
start_date: "20100101"
initial_condition: "AMIPFromERA5"
surface_setup: "PrescribedSurface"
t_end: "186days"
topo_smoothing: true
topography: "Earth"
z_elem: 39
use_sgs_quadrature: true
quadrature_order: 3
