FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/longrun_configs/amip_target_diagedmf.yml"
checkpoint_dt: "720hours"
co2: "maunaloa"
coupler_toml: ["toml/amip.toml"]
dt: "120secs"
dt_cpl: "120secs"
dt_save_state_to_disk: "30days"
dt_save_to_sol: "30days"
dz_bottom: 30.0
energy_check: false
h_elem: 16
land_albedo_type: "map_temporal"
mode_name: "amip"
mono_surface: false
netcdf_output_at_levels: true
output_default_diagnostics: true
radiation_reset_rng_seed: true
rayleigh_sponge: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "6hours"
topography: "Earth"
topo_smoothing: true
turb_flux_partition: "CombinedStateFluxesMOST"
viscous_sponge: true
z_elem: 63
z_max: 60000.0
extra_atmos_diagnostics:
  - short_name: [od550aer, odsc550aer]
    reduction_time: average
    period: "1months"
