FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_diagedmf.yml"
checkpoint_dt: "7days"
coupler_toml: ["toml/amip.toml"]
dt: "120secs"
dt_cpl: "120secs"
energy_check: false
land_model: "integrated"
mode_name: "amip"
netcdf_output_at_levels: true
output_default_diagnostics: true
radiation_reset_rng_seed: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "14days"
topo_smoothing: true
topography: "Earth"
detect_restart_files: true
restart_dir: "/scratch/kphan2/checkpoints"
restart_t: 604800
restart_cache: true
