FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_wx_diagedmf.yml"
coupler_toml: ["toml/wxquest_diagedmf.toml"]
strict_params: false
mode_name: "subseasonal"
# era5_initial_condition_dir: "/net/sampo/data1/wxquest_data/initial_conditions/initial_conditions_v1_dev"
era5_initial_condition_dir: "/net/sampo/data1/wxquest_data/initial_conditions/initial_conditions_v1_dev2"
initial_condition: "WeatherModel"
checkpoint_dt: "7days"
dt: "120secs"
dt_cpl: "120secs"
dt_seaice: "120secs"
energy_check: false
h_elem: 32
land_fraction_source: "era5"
binary_area_fraction: false

### integrated land ###
land_model: "integrated"

### bucket land ###
# land_model: "bucket"
# bucket_albedo_type: "map_temporal"
# bucket_albedo_type: "era5"
# bucket_initial_condition: "/net/sampo/data1/cchristo/WeatherQuest_data/archive_dev4/era5_bucket_processed_20250831_0000.nc"

land_spun_up_ic: false
land_temperature_anomaly: "nothing"
use_land_diagnostics: true
radiation_reset_rng_seed: true
start_date: "19750101"
surface_setup: "PrescribedSurface"
topo_smoothing: true
topography: "Earth"
t_end: "40days"
netcdf_output_at_levels: true
use_coupler_diagnostics: true
extra_atmos_diagnostics:
  - short_name: [zg, orog, tas, ta, mslp, pr, ua, va, ts, rhoa, pfull, hur, hus, clw, cl, hfss, hfls, evspsbl, hussfc, rsds, rlds, rlus, rsus, rld, wa, waup]
    period: 3hours
    reduction_time: inst
  - short_name: [hfss, hfls, evspsbl]
    period: 3hours
    reduction_time: average
# extra_atmos_diagnostics:
#   - short_name: [zg, orog, tas, ta, mslp, pr, ua, va, ts, rhoa, pfull, hur, hus, clw, cli, clivi, clwvi, cl, arup, tke, hfss, hfls, evspsbl, hussfc, rsds, rlds, rlus, rsus, rld, wa, waup]
#     period: 3hours
#     reduction_time: average