FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_wx_progedmf.yml"
coupler_toml: ["toml/amip_progedmf.toml"]
strict_params: false
mode_name: "subseasonal"
era5_initial_condition_dir: "/net/sampo/data1/wxquest_data/initial_conditions"
initial_condition: "WeatherModel"
checkpoint_dt: "7days"
dt: "10secs"
dt_cpl: "10secs"
dt_seaice: "10secs"
energy_check: false
h_elem: 32
land_fraction_source: "era5"
binary_area_fraction: false

### integrated land ###
# land_model: "integrated"
# lai_source: "modis_monthly_climatology"

### bucket land ###
land_model: "bucket"
bucket_albedo_type: "map_temporal"
bucket_initial_condition: "/net/sampo/data1/wxquest_data/initial_conditions/era5_bucket_processed_20250831_0000.nc"

land_spun_up_ic: false
land_temperature_anomaly: "nothing"
use_land_diagnostics: true
radiation_reset_rng_seed: true
start_date: "20250831"
surface_setup: "PrescribedSurface"
topo_smoothing: true
topography: "Earth"
t_end: "7days"
netcdf_output_at_levels: true
use_coupler_diagnostics: true
extra_atmos_diagnostics:
  - short_name: [zg, orog, tas, ta, mslp, pr, ua, va, ts, rhoa, pfull, hur, hus, clw, cli, clivi, clwvi, cl, arup, tke, hfss, hfls, evspsbl, hussfc, rsds, rlds, rlus, rsus, rld, wa, waup]
    period: 3hours
    reduction_time: average
