FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_wx_diagedmf.yml"
coupler_toml: ["toml/amip.toml"]
initial_condition: "WeatherModel"
checkpoint_dt: "93days"
co2_model: "fixed"
coupler_output_dir: "output_quick"
dt: "90secs"
dt_cpl: "90secs"
energy_check: false
h_elem: 16
mode_name: "subseasonal"
era5_initial_condition_dir: "/net/sampo/data1/wxquest_data/initial_conditions"
land_model: "bucket"
bucket_albedo_type: "map_temporal"
land_spun_up_ic: false
land_temperature_anomaly: "nothing"
radiation_reset_rng_seed: true
start_date: "20180901"
surface_setup: "PrescribedSurface"
topo_smoothing: true
topography: "Earth"
netcdf_output_at_levels: true
output_default_diagnostics: false
use_coupler_diagnostics: false
use_land_diagnostics: false
strict_params: false
extra_atmos_diagnostics:
  - short_name: [hfls, hfss, rsus, rlus]
    period: 1months
    reduction_time: average
