# This inherits from config/common_configs/numerics_sphere_he16ze63.yml and config/longrun_configs/amip_target_diagedmf.yml in ClimaAtmos.jl
aerosol_radiation: true
approximate_linear_solve_iters: 2
cloud_model: "quadrature"
co2_model: maunaloa
dt: "120secs"
dt_cloud_fraction: "1hours"
dt_rad: "1hours"
dt_save_state_to_disk: "30days"
dz_bottom: 30.0
edmfx_detr_model: "Generalized"
edmfx_entr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_sgs_diffusive_flux: true
edmfx_sgs_mass_flux: true
edmfx_upwinding: "first_order"
h_elem: 16
implicit_diffusion: true
insolation: "timevarying"
moist: "equil"
netcdf_output_at_levels: true
precip_model: "0M"
prescribe_ozone: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "DST02", "DST03", "DST04", "DST05", "OC1", "OC2", "SO4", "SSLT01", "SSLT02", "SSLT03", "SSLT04", "SSLT05"]
prognostic_tke: true
rad: "allskywithclear"
rayleigh_sponge: true
surface_setup: "DefaultMoninObukhov"
t_end: "120days"
toml: [toml/longrun_aquaplanet_diagedmf.toml]
turbconv: "diagnostic_edmfx"
viscous_sponge: true
z_elem: 63
z_max: 60000.0
