apply_limiter: false
bucket_albedo_type: "map_temporal"
dt: "150secs"
dt_cpl: "150secs"
dt_rad: "1hours"
dz_bottom: 30
h_elem: 4
mode_name: "amip"
moist: "nonequil"
precip_model: "1M"
rad: "gray"
rayleigh_sponge: true
start_date: "20100101"
t_end: "300secs"
time_varying_trace_gases: ["CO2"]
#use_sgs_quadrature: false
vert_diff: "true"
z_elem: 50
z_stretch: false
