apply_limiter: false
checkpoint_dt: "400secs"
detect_restart_files: true
energy_check: false
h_elem: 6
mode_name: "amip"
rad: "allskywithclear"
microphysics_model: "0M"
t_end: "800secs"
time_varying_trace_gases: ["CO2"]
vert_diff: "true"
