apply_limiter: false
co2: "maunaloa"
dt: "150secs"
dt_cpl: "150secs"
dt_rad: "1hours"
dt_save_to_sol: "1days"
dz_bottom: 30
dz_top: 3000
h_elem: 4
land_albedo_type: "map_temporal"
mode_name: "amip"
moist: "equil"
precip_model: "0M"
rad: "gray"
rayleigh_sponge: true
t_end: "300secs"
vert_diff: "true"
z_elem: 50
z_stretch: false
