FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_progedmf.yml"
bucket_albedo_type: "map_temporal"
co2: "maunaloa"
coupler_toml: ["toml/amip_progedmf.toml"]
dt: "30secs"
dt_cpl: "30secs"
dz_bottom: 30.0
energy_check: false
h_elem: 6
mode_name: "amip"
netcdf_output_at_levels: true
output_default_diagnostics: true
radiation_reset_rng_seed: true
rayleigh_sponge: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "60secs"
topo_smoothing: true
topography: "Earth"
viscous_sponge: true
z_elem: 63
z_max: 60000.0
