apply_limiter: false
dt: "150secs"
dt_cpl: "150secs"
dt_rad: "1hours"
dz_bottom: 30
energy_check: false
h_elem: 16
mode_name: "amip"
rad: "gray"
microphysics_model: "0M"
rayleigh_sponge: true
t_end: "300secs"
time_varying_trace_gases: ["CO2"]
vert_diff: "true"
z_elem: 50
z_stretch: false
