apply_limiter: false
dt: "150secs"
dt_cpl: "150secs"
dt_rad: "1hours"
dz_bottom: 30
h_elem: 4
land_model: "integrated"
land_spun_up_ic: false
mode_name: "amip"
rad: "allskywithclear"
microphysics_model: "0M"
rayleigh_sponge: true
t_end: "300secs"
time_varying_trace_gases: ["CO2"]
vert_diff: "true"
z_elem: 50
z_stretch: false
