FLOAT_TYPE: "Float32"
albedo_model: "CouplerAlbedo"
atmos_config_file: "config/atmos_configs/climaatmos_edonly.yml"
coupler_toml: ["toml/amip_diagedmf.toml"]
dt: "240secs"
dt_cpl: "240secs"
dz_bottom: 100.0
energy_check: false
h_elem: 6
land_model: "integrated"
mode_name: "amip"
moist: equil
netcdf_interpolation_num_points: [90, 45, 31]
netcdf_output_at_levels: true
output_default_diagnostics: true
rad: allskywithclear
radiation_reset_rng_seed: true
rayleigh_sponge: true
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "480secs"
topo_smoothing: true
topography: "Earth"
viscous_sponge: true
z_elem: 39
z_max: 60000.0
