apply_limiter: false
co2: "maunaloa"
checkpoint_dt: "400secs"
dt_save_to_sol: "1days"
energy_check: false
h_elem: 6
mode_name: "amip"
moist: "equil"
mono_surface: false
precip_model: "0M"
rad: "allskywithclear"
t_end: "800secs"
vert_diff: "true"
