apply_limiter: false
bucket_albedo_type: "function"
dt: "30mins"
dt_cpl: "150secs"
dt_rad: "1hours"
dz_bottom: 30
h_elem: 16
mode_name: "amip"
moist: "equil"
precip_model: "0M"
rad: "gray"
rayleigh_sponge: true
share_surface_space: false
t_end: "462days"
vert_diff: "true"
z_elem: 50
z_stretch: false
extra_atmos_diagnostics:
  - short_name: [hus, hur, ta]
    period: 1months
    reduction_time: average
    pressure_coordinates: true
    compute_every: 1hours
