apply_limiter: false
dt_atmos: "150secs"
dt_cpl: "150secs"
dt_land: "50secs"
dt_ocean: "30secs"
dt_rad: "1hours"
dt_seaice: "37.5secs"
dz_bottom: 30
energy_check: false
h_elem: 16
land_model: "integrated"
mode_name: "amip"
moist: "equil"
precip_model: "0M"
rad: "gray"
rayleigh_sponge: true
t_end: "600secs"
time_varying_trace_gases: ["CO2"]
vert_diff: "true"
z_elem: 50
z_stretch: false
