apply_limiter: false
dt: "200secs"
dt_cpl: "200secs"
energy_check: true
h_elem: 4
mode_name: "slabplanet"
moist: "equil"
output_default_diagnostics: false
precip_model: "0M"
rad: "gray"
t_end: "1days"
vert_diff: "true"
