apply_limiter: false
conservation_softfail: true
dt: "200secs"
dt_cpl: "200secs"
energy_check: true
evolving_ocean: false
h_elem: 4
mode_name: "slabplanet"
output_default_diagnostics: false
rad: nothing
microphysics_model: "dry"
t_end: "1days"
vert_diff: "true"
