apply_limiter: false
bucket_albedo_type: "function"
dt: "200secs"
dt_cpl: "200secs"
energy_check: true
h_elem: 4
mode_name: "slabplanet"
rad: "gray"
microphysics_model: "0M"
share_surface_space: false
t_end: "1days"
use_itime: false
vert_diff: "true"
