apply_limiter: false
dt: "200secs"
dt_cpl: "200secs"
dt_save_to_sol: "9days"
energy_check: true
h_elem: 4
mode_name: "slabplanet"
moist: "equil"
mono_surface: true
precip_model: "0M"
rad: "gray"
t_end: "10days"
turb_flux_partition: "PartitionedStateFluxes"
vert_diff: "true"
