bucket_albedo_type: "function"
conservation_softfail: true
dt: "200secs"
dt_cpl: "200secs"
h_elem: 4
mode_name: "slabplanet_aqua"
rad: "gray"
microphysics_model: "0M"
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "400secs"
vert_diff: "DecayWithHeightDiffusion"
