apply_limiter: false
conservation_softfail: true
dt: "200secs"
dt_cpl: "200secs"
dt_save_to_sol: "9days"
energy_check: true
h_elem: 4
mode_name: "slabplanet"
moist: "dry"
mono_surface: true
output_default_diagnostics: false
precip_model: nothing
rad: nothing
t_end: "10days"
vert_diff: "true"
