FLOAT_TYPE: "Float32"
atmos_config_file: "config/benchmark_configs/climaatmos_diagedmf_io.yml"
dt: "120secs"
dt_cpl: "120secs"
energy_check: false
land_model: "integrated"
mode_name: "amip"
monthly_checkpoint: false
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "12hours"
use_coupler_diagnostics: true
