FLOAT_TYPE: "Float32"
aerosol_radiation: true
atmos_config_file: "config/benchmark_configs/climaatmos_diagedmf_io.yml"
dt: "120secs"
dt_cpl: "120secs"
energy_check: false
land_model: "integrated"
mode_name: "amip"
monthly_checkpoint: false
prescribe_ozone: true
prescribed_aerosols: ["CB1", "CB2", "DST01", "OC1", "OC2", "SO4", "SSLT01"]
start_date: "20100101"
surface_setup: "PrescribedSurface"
t_end: "12hours"
use_coupler_diagnostics: true
