FLOAT_TYPE: "Float32"
aerosol_radiation: true
approximate_linear_solve_iters: 2
dt: 120secs
dt_cloud_fraction: 1hours
dt_rad: 1hours
dt_save_state_to_disk: "Inf"
dz_bottom: 30.0
h_elem: 30
implicit_diffusion: true
insolation: "timevarying"
output_default_diagnostics: false
prescribed_aerosols: ["CB1", "CB2", "DST01", "DST02", "DST03", "DST04", "DST05", "OC1", "OC2", "SO4", "SSLT01", "SSLT02", "SSLT03", "SSLT04", "SSLT05"]
rad: allskywithclear
surface_setup: DefaultMoninObukhov
t_end: 12hours
time_varying_trace_gases: ["CO2", "O3"]
vert_diff: "DecayWithHeightDiffusion"
z_elem: 63
z_max: 55000.0
microphysics_model: "0M"
