[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ClimaCoreMakie = "908f55d8-4145-4867-9c14-5dad1a479e4d"
ClimaCoupler = "4ade58fe-a8da-486c-bd89-46df092ec0c7"
ClimaOcean = "0376089a-ecfe-4b0e-a64f-9c555d74d754"
ClimaSeaIce = "6ba0ff68-24e6-4315-936c-2e99227c95a4"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Poppler_jll = "9c32591e-4766-534b-9725-b71a8799265b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Documenter = "0.27"
Poppler_jll = "24"
